[build]
  command = """
  mkdir -p build
  cp index.html build/
  cp -r assets build/
  """
  publish = "build/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "https://forex-intelligence-app.streamlit.app"
  status = 301
  force = true

[[redirects]]
  from = "/app/*"
  to = "https://forex-intelligence-app.streamlit.app/:splat"
  status = 301
  force = true