
[server]
port = 5000
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00c7b7"
backgroundColor = "#0f1c2e"
secondaryBackgroundColor = "#1a2c42"
textColor = "#f1f1f1"
